ALTER TABLE players
  ADD COLUMN IF NOT EXISTS report_score_weighted DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS report_muted_until TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS spam_reports_count INTEGER NOT NULL DEFAULT 0;
